apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pokerplanning.fullname" . }}
  labels:
    {{- include "pokerplanning.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pokerplanning.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pokerplanning.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "pokerplanning.serviceAccountName" . }}
      imagePullSecrets:
        - name: tool-image-repository
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.application.image }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "pokerplanning.fullname" . }}
